# Generated by Django 5.1.4 on 2024-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/", verbose_name="프로필 이미지"
            ),
        ),
    ]
