# Generated by Django 5.1.4 on 2024-12-28 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=130)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("template", "Template"),
                            ("maintenance", "Maintenance"),
                            ("develop", "Develop"),
                            ("other", "Other"),
                        ],
                        default="idea",
                        help_text="Category of the product",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        default=0,
                        help_text="Price of the product in thousand units (no decimals)",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="like_products", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
