# Generated by Django 5.1.4 on 2024-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=130, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('idea', 'Idea'), ('template', 'Template'), ('maintenance', 'Maintenance'), ('develop', 'Develop'), ('other', 'Other')], help_text='Category of the product', max_length=30, null=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Price of the product in thousand units (no decimals)', null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
