# Generated by Django 5.1.4 on 2024-12-29 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="saved_users",
            field=models.ManyToManyField(
                related_name="save_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
