# Generated by Django 5.1.4 on 2024-12-29 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_saved_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
