# Generated by Django 5.1.4 on 2024-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_image_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idea", "Idea"),
                    ("template", "Template"),
                    ("maintenance", "Maintenance"),
                    ("develop", "Develop"),
                    ("other", "Other"),
                ],
                default="idea",
                help_text="Category of the product",
                max_length=30,
                null=True,
            ),
        ),
    ]
