# Generated by Django 5.1.4 on 2024-12-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Price of the product in thousand units (no decimals)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("idea", "Idea"),
                    ("template", "Template"),
                    ("maintenance", "Maintenance"),
                    ("develop", "Develop"),
                    ("other", "Other"),
                ],
                default="idea",
                help_text="Category of the product",
                max_length=30,
            ),
        ),
    ]
