# Generated by Django 5.1.4 on 2024-12-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_price_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price of the product in thousand units (no decimals)",
            ),
        ),
    ]
