# Generated by Django 5.1.4 on 2024-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Price of the product in thousand units (no decimals)"
            ),
        ),
    ]
