# Generated by Django 5.1.4 on 2024-12-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Price of the product in thousand units (no decimals)",
            ),
        ),
    ]
