# Generated by Django 5.1.4 on 2024-12-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(
                default=0,
                help_text="Price of the product in thousand units (no decimals)",
                max_length=20,
            ),
        ),
    ]
